In [2]:
!pip install selenium
!pip install beautifulsoup4
!pip install pandas
!pip install webdriver-manager

Requirement already satisfied: selenium in c:\users\lahar\anaconda3\lib\site-packages (4.45.0)
Requirement already satisfied: certifi>=2026.2.25 in c:\users\lahar\anaconda3\lib\site-packages (from selenium) (2026.6.17)
Requirement already satisfied: trio<1.0,>=0.31.0 in c:\users\lahar\anaconda3\lib\site-packages (from selenium) (0.33.0)
Requirement already satisfied: trio-websocket<1.0,>=0.12.2 in c:\users\lahar\anaconda3\lib\site-packages (from selenium) (0.12.2)
Requirement already satisfied: typing_extensions<5.0,>=4.15.0 in c:\users\lahar\anaconda3\lib\site-packages (from selenium) (4.15.0)
Requirement already satisfied: urllib3<3.0,>=2.6.3 in c:\users\lahar\anaconda3\lib\site-packages (from urllib3[socks]<3.0,>=2.6.3->selenium) (2.7.0)
Requirement already satisfied: websocket-client<2.0,>=1.8.0 in c:\users\lahar\anaconda3\lib\site-packages (from selenium) (1.8.0)
Requirement already satisfied: attrs>=23.2.0 in c:\users\lahar\anaconda3\lib\site-packages (from trio<1.0,>=0.31.0->selenium) (25.4.0)
Requirement already satisfied: sortedcontainers in c:\users\lahar\anaconda3\lib\site-packages (from trio<1.0,>=0.31.0->selenium) (2.4.0)
Requirement already satisfied: idna in c:\users\lahar\anaconda3\lib\site-packages (from trio<1.0,>=0.31.0->selenium) (3.11)
Requirement already satisfied: outcome in c:\users\lahar\anaconda3\lib\site-packages (from trio<1.0,>=0.31.0->selenium) (1.3.0.post0)
Requirement already satisfied: sniffio>=1.3.0 in c:\users\lahar\anaconda3\lib\site-packages (from trio<1.0,>=0.31.0->selenium) (1.3.0)
Requirement already satisfied: cffi>=1.14 in c:\users\lahar\anaconda3\lib\site-packages (from trio<1.0,>=0.31.0->selenium) (2.0.0)
Requirement already satisfied: wsproto>=0.14 in c:\users\lahar\anaconda3\lib\site-packages (from trio-websocket<1.0,>=0.12.2->selenium) (1.3.2)
Requirement already satisfied: pysocks!=1.5.7,<2.0,>=1.5.6 in c:\users\lahar\anaconda3\lib\site-packages (from urllib3[socks]<3.0,>=2.6.3->selenium) (1.7.1)
Requirement already satisfied: pycparser in c:\users\lahar\anaconda3\lib\site-packages (from cffi>=1.14->trio<1.0,>=0.31.0->selenium) (2.23)
Requirement already satisfied: h11<1,>=0.16.0 in c:\users\lahar\anaconda3\lib\site-packages (from wsproto>=0.14->trio-websocket<1.0,>=0.12.2->selenium) (0.16.0)
Requirement already satisfied: beautifulsoup4 in c:\users\lahar\anaconda3\lib\site-packages (4.13.5)
Requirement already satisfied: soupsieve>1.2 in c:\users\lahar\anaconda3\lib\site-packages (from beautifulsoup4) (2.5)
Requirement already satisfied: typing-extensions>=4.0.0 in c:\users\lahar\anaconda3\lib\site-packages (from beautifulsoup4) (4.15.0)
Requirement already satisfied: pandas in c:\users\lahar\anaconda3\lib\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\lahar\anaconda3\lib\site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\lahar\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\lahar\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\lahar\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\lahar\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: webdriver-manager in c:\users\lahar\anaconda3\lib\site-packages (4.1.2)
Requirement already satisfied: requests in c:\users\lahar\anaconda3\lib\site-packages (from webdriver-manager) (2.32.5)
Requirement already satisfied: python-dotenv in c:\users\lahar\anaconda3\lib\site-packages (from webdriver-manager) (1.1.0)
Requirement already satisfied: packaging in c:\users\lahar\anaconda3\lib\site-packages (from webdriver-manager) (25.0)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\lahar\anaconda3\lib\site-packages (from requests->webdriver-manager) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\lahar\anaconda3\lib\site-packages (from requests->webdriver-manager) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\lahar\anaconda3\lib\site-packages (from requests->webdriver-manager) (2.7.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\lahar\anaconda3\lib\site-packages (from requests->webdriver-manager) (2026.6.17)

In [3]:
from selenium import webdriver
from selenium.webdriver.common.by import By
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.chrome.service import Service
from bs4 import BeautifulSoup
import pandas as pd
import time

In [4]:
driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()))

driver.maximize_window()

In [5]:
url = "https://www.nykaa.com/mom-and-baby/baby-care/c/14798"
driver.get(url)
time.sleep(5)

In [6]:
for i in range(20):
    driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
    time.sleep(2)

In [7]:
url = "https://www.nykaa.com/mom-and-baby/baby-care/c/14798"

driver.get(url)

time.sleep(5)

In [8]:
for i in range(20):
    driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
    time.sleep(3)

In [9]:
products = driver.find_elements(By.CSS_SELECTOR, "a[href*='/p/']")

print("Products:", len(products))

Products: 31

In [20]:
products = driver.find_elements(By.CSS_SELECTOR, 'a[href*="/p/"]')

print("Products:", len(products))

for i, product in enumerate(products, start=1):
    print(i, product.get_attribute("href"))

Products: 21
1 https://www.nykaa.com/cetaphil-baby-mild-bar/p/17340632?productId=17340632&pps=1
2 https://www.nykaa.com/max-care-virgin-cold-pressed-oil-for-hair-skin-with-coconut/p/832875?productId=832875&pps=2
3 https://www.nykaa.com/aveeno-baby-daily-moisture-wash-shampoo-natural-oat-gentle-cleanser-for-hair-sensitive-body-skin/p/17889837?productId=17889837&pps=3
4 https://www.nykaa.com/orimii-bump-hydrating-whipped-butter-for-pregnancy-stretch-marks/p/10773982?productId=10773982&pps=4
5 https://www.nykaa.com/nat-habit-brahmi-matsyakshi-summer-dasabuti-baby-hair-scalp-oil/p/10346697?productId=10346697&pps=5
6 https://www.nykaa.com/aveeno-baby-daily-moisturising-lotion/p/181560?productId=181560&pps=6
7 https://www.nykaa.com/bare-anatomy-junior-gentle-cleansing-shampoo/p/20731693?productId=20731693&pps=7
8 https://www.nykaa.com/cetaphil-baby-wash-shampoo-with-organic-calendula/p/757131?productId=757131&pps=8
9 https://www.nykaa.com/tuco-intelligent-kids-mild-body-wash/p/12710986?productId=12710986&pps=9
10 https://www.nykaa.com/orimii-belly-treatment-elixir/p/10773989?productId=10773989&pps=10
11 https://www.nykaa.com/aveeno-baby-daily-moisture-lotion/p/17215799?productId=17215799&pps=11
12 https://www.nykaa.com/bioderma-atoderm-intensive-gel-moussant/p/278742?productId=278742&pps=12
13 https://www.nykaa.com/cetaphil-baby-mild-bar/p/757132?productId=757132&pps=13
14 https://www.nykaa.com/sebamed-baby-protective-facial-cream-50ml/p/81070?productId=81070&pps=14
15 https://www.nykaa.com/tuco-intelligent-kids-mild-shampoo/p/12671289?productId=12671289&pps=15
16 https://www.nykaa.com/tuco-intelligent-dull-skin-facewash-for-kids/p/15411746?productId=15411746&pps=16
17 https://www.nykaa.com/nat-habit-pure-virgin-coconut-baby-oil/p/10835164?productId=10835164&pps=17
18 https://www.nykaa.com/cetaphil-baby-soothing-moisturising-cream/p/22166102?productId=22166102&pps=18
19 https://www.nykaa.com/cetaphil-baby-advanced-protection-cream-with-organic-calendula/p/8888289?productId=8888289&pps=19
20 https://www.nykaa.com/sebamed-baby-sun-lotion-spf-50-200-ml/p/130622?productId=130622&pps=20
21 https://www.facebook.com/p/Nykaa-100044142710696/

In [21]:
for i, product in enumerate(products, start=1):
    print(i, product.text, product.get_attribute("href"))

1 Cetaphil Baby Mild Bar
₹1268
₹850
11% Off
Regular price ₹1268. Discounted price ₹850. 11% Off.
( 941 )
2 Sizes https://www.nykaa.com/cetaphil-baby-mild-bar/p/17340632?productId=17340632&pps=1
2 Max Care Virgin Coconut Oil Cold Pressed
Price ₹325.
₹325
( 100024 )
3 Sizes https://www.nykaa.com/max-care-virgin-cold-pressed-oil-for-hair-skin-with-coconut/p/832875?productId=832875&pps=2
3 Aveeno Baby Daily Moisture Wash & Shampoo - Natural Oat Gent...
₹1379
₹1249
9% Off
Regular price ₹1379. Discounted price ₹1249. 9% Off.
( 4603 )
3 Sizes https://www.nykaa.com/aveeno-baby-daily-moisture-wash-shampoo-natural-oat-gentle-cleanser-for-hair-sensitive-body-skin/p/17889837?productId=17889837&pps=3
4 Orimii Bump Hydrating Body Butter for Reducing Stretch Marks...
₹695
₹660
5% Off
Regular price ₹695. Discounted price ₹660. 5% Off.
( 279 ) https://www.nykaa.com/orimii-bump-hydrating-whipped-butter-for-pregnancy-stretch-marks/p/10773982?productId=10773982&pps=4
5 Nat Habit Brahmi Matsyakshi Summer Dasabuti Baby Hair & Scal...
₹435
₹361
17% Off
Regular price ₹435. Discounted price ₹361. 17% Off.
( 161 ) https://www.nykaa.com/nat-habit-brahmi-matsyakshi-summer-dasabuti-baby-hair-scalp-oil/p/10346697?productId=10346697&pps=5
6 Aveeno Baby Daily Moisture Lotion | Oatmeal Face & Body Mois...
₹1050
₹899
14% Off
Regular price ₹1050. Discounted price ₹899. 14% Off.
( 1650 ) https://www.nykaa.com/aveeno-baby-daily-moisturising-lotion/p/181560?productId=181560&pps=6
7 Bare Anatomy Junior Gentle Cleansing Shampoo
₹978
₹860
12% Off
Regular price ₹978. Discounted price ₹860. 12% Off.
( 3736 )
2 Sizes https://www.nykaa.com/bare-anatomy-junior-gentle-cleansing-shampoo/p/20731693?productId=20731693&pps=7
8 Cetaphil Baby Wash & Shampoo with Organic Calendula
₹1499
₹1349
10% Off
Regular price ₹1499. Discounted price ₹1349. 10% Off.
( 1438 ) https://www.nykaa.com/cetaphil-baby-wash-shampoo-with-organic-calendula/p/757131?productId=757131&pps=8
9 TuCo Kids Shower Gel with Tulsi, Saffron, Bodywash to Gently...
₹360
₹328
9% Off
Regular price ₹360. Discounted price ₹328. 9% Off.
( 383 )
1 Size https://www.nykaa.com/tuco-intelligent-kids-mild-body-wash/p/12710986?productId=12710986&pps=9
10 Orimii Belly Treatment Elixir - Body Oil For Stretch Marks; ...
₹695
₹660
5% Off
Regular price ₹695. Discounted price ₹660. 5% Off.
( 238 ) https://www.nykaa.com/orimii-belly-treatment-elixir/p/10773989?productId=10773989&pps=10
11 Aveeno Baby Daily Moisture Lotion | Oatmeal Face & Body Mois...
₹1650
₹1569
5% Off
Regular price ₹1650. Discounted price ₹1569. 5% Off.
( 204 ) https://www.nykaa.com/aveeno-baby-daily-moisture-lotion/p/17215799?productId=17215799&pps=11
12 Bioderma Ultra-Soothing Foaming Gel Atoderm Intensive Gel Mo...
₹849
₹764
10% Off
Regular price ₹849. Discounted price ₹764. 10% Off.
( 2253 ) https://www.nykaa.com/bioderma-atoderm-intensive-gel-moussant/p/278742?productId=278742&pps=12
13 Cetaphil Baby Mild Bar
₹238
₹217
9% Off
Regular price ₹238. Discounted price ₹217. 9% Off.
( 3281 ) https://www.nykaa.com/cetaphil-baby-mild-bar/p/757132?productId=757132&pps=13
14 Sebamed Baby Protective Facial Cream, pH 5.5, Baby Face Crea...
Price ₹1030.
₹1030
( 1395 ) https://www.nykaa.com/sebamed-baby-protective-facial-cream-50ml/p/81070?productId=81070&pps=14
15 TuCo Kids Mild No Tear Shampoo with Reetha & Henna for Gentl...
₹450
₹374
17% Off
Regular price ₹450. Discounted price ₹374. 17% Off.
( 672 )
2 Sizes https://www.nykaa.com/tuco-intelligent-kids-mild-shampoo/p/12671289?productId=12671289&pps=15
16 TuCo Kids Dull Skin Facewash, Dull Skin, Turmeric & Kakadu P...
₹250
₹238
5% Off
Regular price ₹250. Discounted price ₹238. 5% Off.
( 710 ) https://www.nykaa.com/tuco-intelligent-dull-skin-facewash-for-kids/p/15411746?productId=15411746&pps=16
17 Nat Habit Pure Virgin Coconut Baby Oil
₹605
₹484
20% Off
Regular price ₹605. Discounted price ₹484. 20% Off.
( 505 )
2 Sizes https://www.nykaa.com/nat-habit-pure-virgin-coconut-baby-oil/p/10835164?productId=10835164&pps=17
18 Cetaphil Baby Soothing Moisturizing Cream
₹499
₹469
6% Off
Regular price ₹499. Discounted price ₹469. 6% Off.
( 144 )
2 Sizes https://www.nykaa.com/cetaphil-baby-soothing-moisturising-cream/p/22166102?productId=22166102&pps=18
19 Cetaphil Baby Advance Protection Cream
₹749
₹697
7% Off
Regular price ₹749. Discounted price ₹697. 7% Off.
( 1342 ) https://www.nykaa.com/cetaphil-baby-advanced-protection-cream-with-organic-calendula/p/8888289?productId=8888289&pps=19
20 Sebamed Baby Sun Lotion, pH 5.5, Triple Protection From Uv R...
₹1670
₹1253
25% Off
Regular price ₹1670. Discounted price ₹1253. 25% Off.
( 125 ) https://www.nykaa.com/sebamed-baby-sun-lotion-spf-50-200-ml/p/130622?productId=130622&pps=20
21  https://www.facebook.com/p/Nykaa-100044142710696/

In [10]:
links = [p.get_attribute("href") for p in products]

for link in links:
    driver.get(link)

    title = driver.find_element(By.CSS_SELECTOR, "h1").text
    print(title, link)

    driver.back()

Cetaphil Baby Mild Bar
(400g) https://www.nykaa.com/cetaphil-baby-mild-bar/p/17340632?productId=17340632&pps=1
Max Care Virgin Coconut Oil Cold Pressed
(250ml) https://www.nykaa.com/max-care-virgin-cold-pressed-oil-for-hair-skin-with-coconut/p/832875?productId=832875&pps=2
Aveeno Baby Daily Moisture Wash & Shampoo - Natural Oat Gentle Cleanser For Hair, Sensitive Body Skin
(532ml) https://www.nykaa.com/aveeno-baby-daily-moisture-wash-shampoo-natural-oat-gentle-cleanser-for-hair-sensitive-body-skin/p/17889837?productId=17889837&pps=3
Orimii Bump Hydrating Body Butter for Reducing Stretch Marks - Pregnancy Safe
(100ml) https://www.nykaa.com/orimii-bump-hydrating-whipped-butter-for-pregnancy-stretch-marks/p/10773982?productId=10773982&pps=4

ReadTimeoutError: HTTPConnectionPool(host='localhost', port=65127): Read timed out. (read timeout=120)

In [ ]:
from bs4 import BeautifulSoup

product_name = []
original_price = []
discounted_price = []
discount = []
reviews = []

for product in products:
    soup = BeautifulSoup(product.get_attribute("outerHTML"), "html.parser")

    # ---------------- Product Name ----------------
    name_tag = soup.find("h2")
    name = name_tag.get_text(" ", strip=True) if name_tag else "Not Available"

    # ---------------- Original Price ----------------
    mrp_tag = soup.select_one("span.css-17x46n5 span")
    op = mrp_tag.get_text(strip=True) if mrp_tag else ""

    # ---------------- Discounted Price ----------------
    sale_tag = soup.select_one("span.css-111z9ua")
    dp = sale_tag.get_text(strip=True) if sale_tag else op

    # If Original Price is blank, use Discounted Price
    if not op:
        op = dp

    # ---------------- Discount ----------------
    disc_tag = soup.select_one("span.css-cjd9an")
    dis = disc_tag.get_text(strip=True) if disc_tag else "No Discount"

    # ---------------- Reviews ----------------
    review_tag = soup.select_one("span.css-1qbvrhp")
    rev = review_tag.get_text(strip=True) if review_tag else "0"

    # Append results
    product_name.append(name)
    original_price.append(op)
    discounted_price.append(dp)
    discount.append(dis)
    reviews.append(rev)

In [ ]:
type(df)

In [ ]:
df = pd.DataFrame({

    "Product Name": product_name,
    "Original Price": original_price,
    "Discounted Price": discounted_price,
    "Discount": discount,
    "Reviews": reviews

})

# Remove blank product names
df = df[df["Product Name"] != "Not Available"]

# Fill missing Original Price
df["Original Price"] = df["Original Price"].replace("", pd.NA)
df["Original Price"] = df["Original Price"].fillna(df["Discounted Price"])

# Remove duplicate products
df.drop_duplicates(inplace=True)

# Reset index
df.reset_index(drop=True, inplace=True)

In [ ]:
import pandas as pd

data = []

for product in products:
    data.append({
        "URL": product.get_attribute("href")
    })

df = pd.DataFrame(data)

In [ ]:
df.head()

In [ ]:
df.shape

In [ ]:
df.isnull().sum()

In [ ]:
df.to_csv("Nykaa_Baby_Products.csv",index=False)
print("Dataset Saved Successfully")

In [ ]:
df.sample(10)

# EDA part

In [14]:
%who

BeautifulSoup	 By	 ChromeDriverManager	 Service	 driver	 i	 link	 links	 np
pd	 products	 time	 title	 url	 webdriver

In [15]:
type(products)

list

In [16]:
print(products[:2])

[<selenium.webdriver.remote.webelement.WebElement (session="82630c2f02d3b1df6395020223314f5d", element="f.F996A50E2DB8BF4E36F126C6847F7981.d.B5DC45C1D4526DF1186B6D0AE0C864E4.e.855")>, <selenium.webdriver.remote.webelement.WebElement (session="82630c2f02d3b1df6395020223314f5d", element="f.F996A50E2DB8BF4E36F126C6847F7981.d.B5DC45C1D4526DF1186B6D0AE0C864E4.e.875")>]

In [17]:
import pandas as pd

df = pd.DataFrame(products)

In [18]:
df.head()

                                                   0
0  <selenium.webdriver.remote.webelement.WebEleme...
1  <selenium.webdriver.remote.webelement.WebEleme...
2  <selenium.webdriver.remote.webelement.WebEleme...
3  <selenium.webdriver.remote.webelement.WebEleme...
4  <selenium.webdriver.remote.webelement.WebEleme...

In [19]:
import numpy as np

df.replace(r'^\s*$', np.nan, regex=True, inplace=True)
df.dropna(inplace=True)

In [23]:
df.to_csv("cleaned_nykaa_baby_products.csv", index=False)

In [21]:
import numpy as np
df = df.replace(r'^\s*$', np.nan, regex=True)

In [24]:
len(products)

31

In [25]:
type(products)

list

In [26]:
print(products[0])

<selenium.webdriver.remote.webelement.WebElement (session="82630c2f02d3b1df6395020223314f5d", element="f.F996A50E2DB8BF4E36F126C6847F7981.d.B5DC45C1D4526DF1186B6D0AE0C864E4.e.855")>

In [27]:
{
    "Product Name": "...",
    "Original Price": "...",
    "Discounted Price": "...",
    "Discount": "...",
    "Reviews": "..."
}

{'Product Name': '...',
 'Original Price': '...',
 'Discounted Price': '...',
 'Discount': '...',
 'Reviews': '...'}

In [28]:
import pandas as pd

df = pd.DataFrame(products)

In [29]:
df.head()

                                                   0
0  <selenium.webdriver.remote.webelement.WebEleme...
1  <selenium.webdriver.remote.webelement.WebEleme...
2  <selenium.webdriver.remote.webelement.WebEleme...
3  <selenium.webdriver.remote.webelement.WebEleme...
4  <selenium.webdriver.remote.webelement.WebEleme...

In [30]:
import numpy as np

df.replace(r'^\s*$', np.nan, regex=True, inplace=True)
df.dropna(inplace=True)

In [31]:
df.to_csv("cleaned_nykaa_baby_products.csv", index=False)

In [32]:
print(products[0])

<selenium.webdriver.remote.webelement.WebElement (session="82630c2f02d3b1df6395020223314f5d", element="f.F996A50E2DB8BF4E36F126C6847F7981.d.B5DC45C1D4526DF1186B6D0AE0C864E4.e.855")>

In [39]:
import numpy as np

# Convert blank cells to NaN
df.replace(r'^\s*$', np.nan, regex=True, inplace=True)

# Remove rows with any missing values
df.dropna(inplace=True)

# Check if any missing values remain
print(df.isnull().sum())

0    0
dtype: int64

In [42]:
import pandas as pd
import numpy as np

In [43]:
df = pd.read_csv(r"C:\Users\lahar\Downloads\Nykaa_Baby_Products.xls")

In [44]:
df.head()

,Product Name,Original Price,Discounted Price,Discount,Reviews
0,Cetaphil Baby Mild Bar,₹1268,₹850,11% Off,(941)
1,Max Care Virgin Coconut Oil Cold Pressed,NaN,₹325,No Discount,(100024)
2,Aveeno Baby Daily Moisture Wash & Shampoo - Na...,₹1379,₹1249,9% Off,(4603)
3,Orimii Bump Hydrating Body Butter for Reducing...,₹695,₹660,5% Off,(279)
4,Nat Habit Brahmi Matsyakshi Summer Dasabuti Ba...,₹435,₹361,17% Off,(161)

In [45]:
df.replace(r'^\s*$', np.nan, regex=True, inplace=True)

In [46]:
df.dropna(inplace=True)

In [47]:
print(df.isnull().sum())

Product Name        0
Original Price      0
Discounted Price    0
Discount            0
Reviews             0
dtype: int64

In [48]:
df.to_csv("cleaned_nykaa_baby_products.csv", index=False)